import Image from "next/image";
import styles from "./page.module.css";
import Heropage from "./components/heropage";

// export const metadata = {
//   title: "Movie App",
//   description: "Generated by create next app",
// };

export default function Home() {
  return (
    <main children={styles.back}>
      <Heropage />
    </main>
  );
}
